name: GitHub Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pac-Man contribution graph
        uses: yoshi389111/github-pacman-contribution-graph@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          output_dir: .
